/*
 * This test script is automatically generated by Nifty.
 * 
 * The test script is a standalone version that does not require Nifty
 * to run. 
 * 
 * http://parapluu.github.io/nifty-contiki/about
 */
{% for Id in init_motes %}
mote{{Id}}=null;
{% endfor %}

while 
({% for Id in init_motes %}
  (mote{{Id}}==null) ||
{% endfor %}  false) {
{% for Id in init_motes %}
   if (id == {{Id}}) {
      mote{{Id}} = mote;
   }
{% endfor %}
   YIELD();
}

{% for call in calls %}
   {% with type=call|getNth:3 %}
      {% include "scriptlib/calls.tpl" %}
   {% endwith %}
{% endfor %}
